targets:
  $default:
    builders:
      firebase_crud_generator|firestoreRepositoryBuilder:
        enabled: true
      firebase_crud_generator|firestoreCrudBuilder:
        enabled: true

builders:
  firestore_crud_builder:
    target: ":firebase_crud_generator"
    import: "package:firebase_crud_generator/builder.dart"
    builder_factories: ["firestoreRepositoryBuilder", "firestoreCrudBuilder"]
    build_extensions: { ".dart": [".firebase.g.dart"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
