name: firebase_crud_generator
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: Tim Whiting <tim@whitings.org>

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  analyzer: ^0.39.0
  build: ^1.0.0
  build_config: ^0.4.0
  source_gen: "^0.9.0"
  quiver: ">=0.21.0 <3.0.0"
  firebase_crud:
    path: ../firebase_crud
    # git:
    #   url: https://github.com/TimWhiting/firebase_crud
    #   path: firebase_crud

dev_dependencies:
  pedantic: "^1.8.0"
  test: "^1.6.0"
  build_test: "^0.10.3"
  build_runner: "^1.0.0"
  logging: "^0.11.0"
