name: firebase_crud
description: A firebase crud library, use it with the generator to generate extension methods for your classes
# version: 1.0.0
# homepage: https://www.example.com
# author: Tim Whiting <tim@whitings.org>

environment:
  sdk: ">=2.5.0 <3.0.0"

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
